---
name: cmpsc-100-fall-2018-lab6
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        labsix/ManipulateDna.java:
            --single 4 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 8
            --fragment "new Date(" --count 1 --exact
            --fragment "TODO" --count 0 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 2 --exact
    --words 100
# --> check the number of commits beyond a threshold
--commits 14
# --> check that the program executes and produces set lines of output
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 8 --exact
